name: Build and Deploy Docs
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Create document
        run: yarn docs

      - name: Deploy document
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: docs
          folder: docs
